# This is a basic workflow to help you get started with Actions
name: CI StagingDB
# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the staging branch
  push:
    branches:
      - staging
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "migrate"
  migrate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # gives the job access to the secrets and protection settings scoped to the staging environment
    environment: Staging
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs multiple commands using the runners shell
      - name: Flyway Migration
  # You may pin to the exact commit or the version.
  # uses: joshuaavalon/flyway-action@3a2d033344e62315c7b4d2e1b6c9fcfea798e3e6
        uses: joshuaavalon/flyway-action@v2
        with: 
    # The jdbc url to use to connect to the database
         url: jdbc:postgresql://${{secrets.DB_HOST}}:5432/${{secrets.DB_NAME}}
    # The user to use to connect to the database
         user: ${{secrets.DB_USER}}
    # The password to use to connect to the database
         password: ${{secrets.DB_PASS}}
    # Comma-separated list of locations to scan recursively for migrations
         locations: "filesystem:migrations"
